# Generated by Django 4.1.2 on 2023-09-26 05:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='author_name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='author_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=250, overwrite=True, populate_from='title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='blog_status')),
                ('image', models.ImageField(blank=True, max_length=250, null=True, upload_to='blog_images/')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='publication date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts_author', to='api.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_category', to='api.category')),
            ],
        ),
    ]
